// Code generated by go-swagger; DO NOT EDIT.

package logistic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/yusrilsabir22/orderfaz/docs-svc/models"
)

// NewMixin4Params creates a new Mixin4Params object
//
// There are no default values defined in the spec.
func NewMixin4Params() Mixin4Params {

	return Mixin4Params{}
}

// Mixin4Params contains all the bound params for the mixin4 operation
// typically these are obtained from a http.Request
//
// swagger:parameters Mixin4
type Mixin4Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Authorzation(Bearer random_value)
	  Required: true
	  In: header
	*/
	Authorization string
	/*Create a new logistic data
	  Required: true
	  In: body
	*/
	Create *models.PbCreateLogisticRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewMixin4Params() beforehand.
func (o *Mixin4Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindAuthorization(r.Header[http.CanonicalHeaderKey("Authorization")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PbCreateLogisticRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("create", "body", ""))
			} else {
				res = append(res, errors.NewParseError("create", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Create = &body
			}
		}
	} else {
		res = append(res, errors.Required("create", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthorization binds and validates parameter Authorization from header.
func (o *Mixin4Params) bindAuthorization(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Authorization", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Authorization", "header", raw); err != nil {
		return err
	}
	o.Authorization = raw

	return nil
}
