// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbClaimResponse pb claim response
//
// swagger:model pb.ClaimResponse
type PbClaimResponse struct {

	// standard claims
	StandardClaims *PbStandardClaims `json:"standardClaims,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this pb claim response
func (m *PbClaimResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStandardClaims(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbClaimResponse) validateStandardClaims(formats strfmt.Registry) error {
	if swag.IsZero(m.StandardClaims) { // not required
		return nil
	}

	if m.StandardClaims != nil {
		if err := m.StandardClaims.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("standardClaims")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("standardClaims")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this pb claim response based on the context it is used
func (m *PbClaimResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStandardClaims(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PbClaimResponse) contextValidateStandardClaims(ctx context.Context, formats strfmt.Registry) error {

	if m.StandardClaims != nil {
		if err := m.StandardClaims.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("standardClaims")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("standardClaims")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PbClaimResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbClaimResponse) UnmarshalBinary(b []byte) error {
	var res PbClaimResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
