// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbCreateLogisticResponse pb create logistic response
//
// swagger:model pb.CreateLogisticResponse
type PbCreateLogisticResponse struct {

	// id
	ID string `json:"id,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`
}

// Validate validates this pb create logistic response
func (m *PbCreateLogisticResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb create logistic response based on context it is used
func (m *PbCreateLogisticResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbCreateLogisticResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbCreateLogisticResponse) UnmarshalBinary(b []byte) error {
	var res PbCreateLogisticResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
