// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbLoginResponse pb login response
//
// swagger:model pb.LoginResponse
type PbLoginResponse struct {

	// message
	Message string `json:"message,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this pb login response
func (m *PbLoginResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb login response based on context it is used
func (m *PbLoginResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbLoginResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbLoginResponse) UnmarshalBinary(b []byte) error {
	var res PbLoginResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
