// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbRegisterRequest pb register request
//
// swagger:model pb.RegisterRequest
type PbRegisterRequest struct {

	// msisdn
	Msisdn string `json:"msisdn,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this pb register request
func (m *PbRegisterRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb register request based on context it is used
func (m *PbRegisterRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbRegisterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbRegisterRequest) UnmarshalBinary(b []byte) error {
	var res PbRegisterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
