// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbStandardClaims pb standard claims
//
// swagger:model pb.StandardClaims
type PbStandardClaims struct {

	// audience
	Audience string `json:"audience,omitempty"`

	// expires at
	ExpiresAt int64 `json:"expiresAt,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// issued at
	IssuedAt int64 `json:"issuedAt,omitempty"`

	// issuer
	Issuer string `json:"issuer,omitempty"`

	// not before
	NotBefore int64 `json:"notBefore,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this pb standard claims
func (m *PbStandardClaims) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb standard claims based on context it is used
func (m *PbStandardClaims) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbStandardClaims) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbStandardClaims) UnmarshalBinary(b []byte) error {
	var res PbStandardClaims
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
