---
version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "orderfaz"
      POSTGRES_DB: "orderfaz"
      POSTGRES_PASSWORD: "orderfaz"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  dbtest:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "orderfaz"
      POSTGRES_DB: "test_orderfaz"
      POSTGRES_PASSWORD: "orderfaz"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./.test_data/postgresql:/var/lib/postgresql/data/pgdata
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
networks:
   default: