// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yusrilsabir22/orderfaz/docs-svc/models"
)

// Mixin0OKCode is the HTTP code returned for type Mixin0OK
const Mixin0OKCode int = 200

/*
Mixin0OK OK

swagger:response mixin0OK
*/
type Mixin0OK struct {

	/*
	  In: Body
	*/
	Payload *models.PbRegisterResponse `json:"body,omitempty"`
}

// NewMixin0OK creates Mixin0OK with default headers values
func NewMixin0OK() *Mixin0OK {

	return &Mixin0OK{}
}

// WithPayload adds the payload to the mixin0 o k response
func (o *Mixin0OK) WithPayload(payload *models.PbRegisterResponse) *Mixin0OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mixin0 o k response
func (o *Mixin0OK) SetPayload(payload *models.PbRegisterResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *Mixin0OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Mixin0UnauthorizedCode is the HTTP code returned for type Mixin0Unauthorized
const Mixin0UnauthorizedCode int = 401

/*
Mixin0Unauthorized Unauthorized

swagger:response mixin0Unauthorized
*/
type Mixin0Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.PbLoginResponse `json:"body,omitempty"`
}

// NewMixin0Unauthorized creates Mixin0Unauthorized with default headers values
func NewMixin0Unauthorized() *Mixin0Unauthorized {

	return &Mixin0Unauthorized{}
}

// WithPayload adds the payload to the mixin0 unauthorized response
func (o *Mixin0Unauthorized) WithPayload(payload *models.PbLoginResponse) *Mixin0Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mixin0 unauthorized response
func (o *Mixin0Unauthorized) SetPayload(payload *models.PbLoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *Mixin0Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Mixin0ForbiddenCode is the HTTP code returned for type Mixin0Forbidden
const Mixin0ForbiddenCode int = 403

/*
Mixin0Forbidden Forbidden

swagger:response mixin0Forbidden
*/
type Mixin0Forbidden struct {

	/*
	  In: Body
	*/
	Payload *models.PbLoginResponse `json:"body,omitempty"`
}

// NewMixin0Forbidden creates Mixin0Forbidden with default headers values
func NewMixin0Forbidden() *Mixin0Forbidden {

	return &Mixin0Forbidden{}
}

// WithPayload adds the payload to the mixin0 forbidden response
func (o *Mixin0Forbidden) WithPayload(payload *models.PbLoginResponse) *Mixin0Forbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mixin0 forbidden response
func (o *Mixin0Forbidden) SetPayload(payload *models.PbLoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *Mixin0Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
