// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/yusrilsabir22/orderfaz/docs-svc/models"
)

// NewMixin0Params creates a new Mixin0Params object
//
// There are no default values defined in the spec.
func NewMixin0Params() Mixin0Params {

	return Mixin0Params{}
}

// Mixin0Params contains all the bound params for the mixin0 operation
// typically these are obtained from a http.Request
//
// swagger:parameters Mixin0
type Mixin0Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Register User
	  Required: true
	  In: body
	*/
	Register *models.PbRegisterRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewMixin0Params() beforehand.
func (o *Mixin0Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PbRegisterRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("register", "body", ""))
			} else {
				res = append(res, errors.NewParseError("register", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Register = &body
			}
		}
	} else {
		res = append(res, errors.Required("register", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
