// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// Mixin1HandlerFunc turns a function with the right signature into a mixin1 handler
type Mixin1HandlerFunc func(Mixin1Params) middleware.Responder

// Handle executing the request and returning a response
func (fn Mixin1HandlerFunc) Handle(params Mixin1Params) middleware.Responder {
	return fn(params)
}

// Mixin1Handler interface for that can handle valid mixin1 params
type Mixin1Handler interface {
	Handle(Mixin1Params) middleware.Responder
}

// NewMixin1 creates a new http.Handler for the mixin1 operation
func NewMixin1(ctx *middleware.Context, handler Mixin1Handler) *Mixin1 {
	return &Mixin1{Context: ctx, Handler: handler}
}

/*
	Mixin1 swagger:route POST /auth/validate Auth mixin1

# Get private claims data of the token

Validate the token and return claims data
*/
type Mixin1 struct {
	Context *middleware.Context
	Handler Mixin1Handler
}

func (o *Mixin1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewMixin1Params()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
