// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yusrilsabir22/orderfaz/docs-svc/models"
)

// PostAuthLoginOKCode is the HTTP code returned for type PostAuthLoginOK
const PostAuthLoginOKCode int = 200

/*
PostAuthLoginOK OK

swagger:response postAuthLoginOK
*/
type PostAuthLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.PbLoginResponse `json:"body,omitempty"`
}

// NewPostAuthLoginOK creates PostAuthLoginOK with default headers values
func NewPostAuthLoginOK() *PostAuthLoginOK {

	return &PostAuthLoginOK{}
}

// WithPayload adds the payload to the post auth login o k response
func (o *PostAuthLoginOK) WithPayload(payload *models.PbLoginResponse) *PostAuthLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth login o k response
func (o *PostAuthLoginOK) SetPayload(payload *models.PbLoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuthLoginUnauthorizedCode is the HTTP code returned for type PostAuthLoginUnauthorized
const PostAuthLoginUnauthorizedCode int = 401

/*
PostAuthLoginUnauthorized Unauthorized

swagger:response postAuthLoginUnauthorized
*/
type PostAuthLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.PbLoginResponse `json:"body,omitempty"`
}

// NewPostAuthLoginUnauthorized creates PostAuthLoginUnauthorized with default headers values
func NewPostAuthLoginUnauthorized() *PostAuthLoginUnauthorized {

	return &PostAuthLoginUnauthorized{}
}

// WithPayload adds the payload to the post auth login unauthorized response
func (o *PostAuthLoginUnauthorized) WithPayload(payload *models.PbLoginResponse) *PostAuthLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth login unauthorized response
func (o *PostAuthLoginUnauthorized) SetPayload(payload *models.PbLoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
